---
deployment:
  tasks:
    - export DEPLOYPATH=/home/leostore/public_html/
    - index.php $DEPLOYPATH
    - cphp composer install
    - php composer dumpautoload -o
    - php artisan config:cache
    - php artisan route:cache
    
    